<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Innovexa Labs About Page">
        <meta name="keywords" content="Innovexa, Labs, About">
        <meta name="author" content="G05">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>About - Innovexa Labs</title>
        <link href="styles/aboutStyles.css" rel="stylesheet">
        <link href="styles/styles.css" rel="stylesheet">
    </head>
    <body>
        <!-- Header -->
  <header>
    <!-- Logo image was generated by ChatGPT -->
    <div class="header-container">
      <div class="logo-section">
        <img src="images/logo.png" alt="Innovexa Labs Logo" class="logo">
      </div>
      <nav>
        <ul>
          <li><a href="index.html">Home</a></li>
          <li><a href="jobs.html">Jobs</a></li>
          <li><a href="apply.html">Apply</a></li>
          <li><a href="about.html" aria-current="page">About</a></li>
        </ul>
      </nav>
    </div>
  </header>
        <h2>About</h2>
        <main id="about">
            <section id="TimeTable">
                <h2>Class Info</h2>
                <p><strong>Intro to Web Development COS10026</strong></p>
                <ul>
                    <li>Monday Live Lecture 
                        <ul>
                            <li>11:30 AM &ndash; 12:30 PM</li>
                        </ul>
                    </li>
                    <li>Tuesday Workshop
                        <ul>
                            <li>2:30 PM &ndash; 4:30 PM</li>
                        </ul>
                    </li>
                </ul>
            </section>

            <section id="CandQ">
                <h2>Contributions and Quotes</h2>
                <dl>
                    <dt>Andrew<span class="student-id">ID: 106273840</span></dt>
                    <dd>Index Page, Apply (little)</dd>
                    <dd>Language: English &lbrack;first&rbrack;, Japanese &lbrack;fav&rbrack;. Quote:"一期一会"</dd>

                    <dt>Lewis<span class="student-id">ID: 105921300</span></dt>
                    <dd>About Page</dd>
                    <dd>Language: English &lbrack;first&rbrack;, Italian &lbrack;fav&rbrack;. Quote:"Amo programmare, amo programmare,<br> amo programmare, funziona! Aiuto"</dd>

                    <dt>Dillon<span class="student-id">ID: 106045201</span></dt>
                    <dd>Jobs Page, Header, Nav menu</dd>
                    <dd>Language: English &lbrack;first&rbrack;, German &lbrack;fav&rbrack;. Quote:"Ich denke, also bin ich"</dd>

                    <dt>Ridowan<span class="student-id">ID: 103534450</span></dt>
                    <dd>Apply page, Index, Header, Footer, Logo</dd>
                    <dd>Language: Bengali &lbrack;first&rbrack;, English &lbrack;fav&rbrack;. Quote:"নেশা কে না বলুন"</dd>
                </dl>
            </section>

            <section id="GPhoto">
                <h2>Group Photo</h2>
                <figure>
                    <img src="images/group-photo.jpg" alt="Innovexa Team Photo" width="600" height="400">
                    <figcaption>Innovexa Team Photo</figcaption>
                </figure>
            </section>

            <section id="FunFacts">
                <h2>Fun Facts</h2>
                <table>
                    <caption>Innovexa Team Member Fun Facts</caption>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Dream Job</th>
                            <th>Coding Snack</th>
                            <th>Hometown</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Andrew</td>
                            <td>Data Scientist</td>
                            <td>Trail mix</td>
                            <td>Melbourne</td>
                        </tr>
                        <tr>
                            <td>Lewis</td>
                            <td>UX Designer</td>
                            <td>Dark chocolate</td>
                            <td>Melbourne</td>
                        </tr>
                        <tr>
                            <td>Dillon</td>
                            <td>Game Developer</td>
                            <td>Pizza</td>
                            <td>Melbourne</td>
                        </tr>
                        <tr>
                            <td>Ridowan</td>
                            <td>Computor Scientist</td>
                            <td>Pizza</td>
                            <td>Melbourne</td>
                        </tr>
                    </tbody>
                </table>
            </section>
        </main>
        <!-- Footer -->
  <footer>
    <p>&copy; 2025 Innovexa Labs — Where Technology Meets Design.</p>
    <p>
      <a href="https://github.com/RidowanShadid/Assignment01.git" target="_blank">GitHub</a> | 
      <a href="https://student-team-ba33pq9o.atlassian.net/jira/software/projects/WEB/boards/68" target="_blank">Jira Project</a>
    </p>
    <p>Contact Us: <a href="mailto:info@innovexalabs.com">info@innovexalabs.com</a></p>
  </footer>
    </body>
</html>