<footer>
    <p>&copy; 2025 Innovexa Labs — Where Technology Meets Design.</p>
    <p>
        <!-- Footer links -->
        <a href="https://github.com/RidowanShadid/Assignment01.git" target="_blank">Part 1 GitHub</a> | 
        <a href="https://github.com/RidowanShadid/Assignment02" target="_blank">Part 2 GitHub</a> | 
        <a href="https://student-team-ba33pq9o.atlassian.net/jira/software/projects/WEB/boards/68" target="_blank">Jira Project</a>
    </p>
    <p>Contact Us: <a href="mailto:info@innovexalabs.com">info@innovexalabs.com</a></p>
</footer>