<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Listing of available jobs for Innovexa Labs ">
    <meta name="keywords" content="Jobs, Product design, Innovexa labs, startup careers">
    <meta name="author" content="Dillon Thomas">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Work With Us</title>
    <link rel="stylesheet" href="styles/styles.css">
    

</head> 

<body>
    <header>
        <div class="header-container">
            <div class="logo-section">
                <!-- Logo image was generated by ChatGPT -->
                <img src="images/logo.png" alt="Innovexa Labs Logo" class="logo">
            </div>
            <nav>
                <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php" aria-current="page">Jobs</a></li>
                <li><a href="apply.php">Apply</a></li>
                <li><a href="about.php">About</a></li>
                </ul>
            </nav>
        </div>
        <aside id="jobs-aside">
            <h2>How to apply</h2>
            <!--"How to apply" content generated by chatgpt-->
            <ol> <!--ordered list requirement-->
                <li>Prepare a CV (PDF format, maximum 2 pages).</li>
                <li>Include links to your portfolio, GitHub, or other work samples.</li>
                <li>Write a short cover note explaining why you’d like to join Innovexa Labs</li>
                <li>Email your application to <a href= "careers@innovexalabs.com">careers@innovexalabs.com</a> with the role reference number in the subject line</li>
                <li>Fill out our form below</li>
            </ol>
            <p id="apply-button"><a href="apply.php">APPLY NOW</a></p> <!--apply button links to apply page-->
        </aside>
    </header>

    <main>
    <section id="page-info">
    <h1 id="title">Work with us</h1>
    <!-- "Work with us" content generated by chatgpt -->
    <p>At Innovexa Labs, we’re building a new generation of digital products that blend cutting-edge design with robust engineering. We’re looking for talented people who want to shape the future with us.</p>
    </section>
    
    <h2>Available positions</h2>
    <!--JOB 1-->
    <section id="job-01" class="job-card"> 
        <!-- Job 1 and Job 2s content generated by chatgpt-->
        <h3>Senior Product Designer</h3>
        <p>Ref: IPD01</p> <!--5 alphanumeric-->
        <p>Salary:AU$135,000 – AU$160,000 + equity options</p>
        <p>Reports to: Head of product</p>
        <p>Description: You will lead product design for our analytics platform, creating experiences that turn complex data into intuitive and accessible workflows. </p>
        <h4>Key responsibilites:</h4>
        <ul> <!--unordered list requirement-->
            <li>Conduct discovery sessions with customers and translate insights into design outcomes.</li>
            <li>Develop user flows, wireframes, prototypes, and high-fidelity UI.</li>
            <li>Maintain and evolve the design system in partnership with engineering.</li>
            <li>Champion accessibility standards (WCAG 2.2).</li>
            <li>Measure design impact through product metrics and user feedback.</li>  
        </ul>

        <h4>Essential Requirements:</h4>
        <ul>
            <li>Strong portfolio showcasing shipped B2B or SaaS product design.</li>
            <li>Expertise in interaction design, prototyping, and design tools (e.g., Figma).</li>
            <li>Demonstrated knowledge of accessibility principles.</li>
            <li>Excellent collaboration skills with engineers and product managers.</li> 
        </ul>

        <h4>Preferable Requirements:</h4>
        <ul>
            <li>Experience with design systems at scale.</li>
            <li>Familiarity with analytics, dashboards, or business intelligence tools.</li>
            <li>Understanding of basic front-end technologies (HTML, CSS).</li>
        </ul>
    </section>
    <!--JOB 2 (position descriptions and details generated using chatgpt)-->
    <section id="job-02" class="job-card"> 
        <h3>Frontend Engineer — Design Systems</h3>
        <p>Ref: IFE02</p>
        <p>Salary: AU$125,000 – AU$145,000 + equity options</p>
        <p>Description: You will build and maintain our component library and theming system, ensuring our design language is accessible, consistent, and fast to implement across products.</p>
        <p>Reports to: Engineering Manager</p>
        <h4>Key responsibilites:</h4>
        <ul>
            <li>Develop reusable, documented UI components with semantic HTML and modern CSS.</li>
            <li>Collaborate with design to implement tokens, patterns, and accessibility best practice.</li>
            <li>Optimise frontend performance, reliability, and scalability</li>
            <li>Support automated testing and CI/CD pipelines for the design system.</li>
            <li>Provide mentorship and guidance on frontend best practice.</li>
        </ul>
        <h4>Essential Requirements:</h4>
        <ul>
            <li>Proficiency in semantic HTML5 and CSS3, including responsive design.</li>
            <li>Strong understanding of accessibility (focus states, keyboard navigation, contrast).</li>
            <li>Experience with version control (Git) and collaborative workflows.</li>
            <li>Ability to translate design specifications into functional, maintainable code.</li> 
        </ul>
        
        <h4>Preferable Requirements:</h4>
        <ul>
            <li>Knowledge of design tokens and component-driven development.</li>
            <li>Familiarity with analytics or data-visualisation interfaces.</li>
            <li>Experience with performance profiling and bundle optimisation.</li>
        </ul>
    </section>
    </main>
    <!-- ================== FOOTER ================== -->
    <?php include_once "footer.inc"; ?>
    
</body>
</html>