<?php
    session_start(); 
?>
<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Listing of available jobs for Innovexa Labs ">
    <meta name="keywords" content="Jobs, Product design, Innovexa labs, startup careers">
    <meta name="author" content="Dillon Thomas">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Work With Us</title>
    <link rel="stylesheet" href="styles/styles.css">
    

</head> 

<body>
    <!-- ================== HEADER ================== -->
    <?php include_once "header.inc"; ?>
    <aside id="jobs-aside">
            <h2>How to apply</h2>
            <!--"How to apply" content generated by chatgpt-->
            <ol> <!--ordered list requirement-->
                <li>Prepare a CV (PDF format, maximum 2 pages).</li>
                <li>Include links to your portfolio, GitHub, or other work samples.</li>
                <li>Write a short cover note explaining why you’d like to join Innovexa Labs</li>
                <li>Email your application to <a href= "careers@innovexalabs.com">careers@innovexalabs.com</a> with the role reference number in the subject line</li>
                <li>Fill out our form below</li>
            </ol>
            <p id="apply-button"><a href="apply.php">APPLY NOW</a></p> <!--apply button links to apply page-->
    </aside>

    <main>
    <section id="page-info">
    <h1 id="title">Work with us</h1>
    <!-- "Work with us" content generated by chatgpt -->
    <p>At Innovexa Labs, we’re building a new generation of digital products that blend cutting-edge design with robust engineering. We’re looking for talented people who want to shape the future with us.</p>
    </section>

    
<!-- template code for table from lab09/module 9-->
    <section id="jobs-table" class="jobs-card">
    <h2>Available positions</h2>
    <?php
	 require_once "settings.php";	// Load MySQL log in credentials 
	 $conn = @mysqli_connect ($host,$username,$password,$database);	// Log in and use database
	 if ($conn) { // check is database is available for use
		$query = "SELECT * from `jobs`";	// query selects all data entries for jobs table 
		$result = mysqli_query ($conn, $query);
        //to check if a MySQL query result set contains one or more rows
        if ($result->num_rows > 0) 
        {
            echo "<br>
            <table>
                <tr>
                    <th>Reference</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Salary</th>
                    <th>Reporting To</th>
                    <th>Key Responsibilities</th>
                    <th>Essential Rsponsibilites</th>
                    <th>Preferable Requirements</th>
                </tr>";
            while ($row = mysqli_fetch_assoc($result)) {
                echo "<tr>";
                    echo "<td>" . $row['jobs_ref'] . "</td>";
                    echo "<td>" . $row['title'] . "</td>";
                    echo "<td>" . $row['short_desc'] . "</td>";
                    echo "<td>" . $row['salary'] . "</td>";
                    echo "<td>" . $row['reporting_line'] . "</td>";
                    echo "<td>" . $row['responsibilities'] . "</td>";
                    echo "<td>" . $row['essential'] . "</td>";
                    echo "<td>" . $row['preferable'] . "</td>";
                echo "</tr>";
            }
            echo "</table>";
        } 
        else {
            echo "There are no jobs to display";
        }
		mysqli_close ($conn);					// Close the database connect
	 }else {
		echo "<p>Unable to connect to the database.</p>";
	 }
    ?>
    </section>
    </main>
    <!-- ================== FOOTER ================== -->
    <?php include_once "footer.inc"; ?>
    
</body>
</html>